const express = require('express');
const mongoose = require('mongoose');
const authRoutes = require('./routes/auth');
const destinationRoutes = require('./routes/destinations');
const favoritesRoutes = require('./routes/favorites');
const tripRoutes = require('./routes/trips');
const userRoutes = require('./routes/users');
require('dotenv').config();

const app = express();
const isDev = process.env.NODE_ENV !== 'production';

if (isDev) {
  try {
    const livereload = require('livereload');
    const connectLiveReload = require('connect-livereload');
    const liveReloadServer = livereload.createServer({
      exts: ['html', 'css', 'js'],
      delay: 100
    });

    liveReloadServer.watch(__dirname + '/public');
    app.use(connectLiveReload());
  } catch (error) {
    console.warn('Live reload disabled:', error.message);
  }
}

app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ limit: '10mb', extended: true }));
app.use('/api/auth', authRoutes);// This is for user registration and login, generated by ai lah later phrase 2 we add more auth features like JWT, password hashing, etc.)
app.use('/api/users', userRoutes);
app.use('/api/trips', tripRoutes);
app.use('/api/destinations', destinationRoutes);
app.use('/api/favorites', favoritesRoutes);

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URL, {
  serverSelectionTimeoutMS: 3000, // stop trying after 3s
  family: 4 // Force IPv4 to fix mobile network issues
})
  .then(() => console.log("MongoDB connected"))
  .catch(err => {
    console.log("MongoDB failed try to resolve connection:");
    console.log(err.message);
  });

// Serve all static files from public/
app.use(express.static('public'));

app.listen(3000, () => console.log(`Server running on http://localhost:3000 (${isDev ? 'dev with live reload' : 'production'})`));

// create a new route just to send google maps key to frontend
app.get('/api/config/maps', (req, res) => {
  res.json({ apiKey: process.env.GOOGLE_MAPS_API_KEY });
})
