const express = require('express');
const mongoose = require('mongoose');
const authRoutes = require('./routes/auth');
const destinationRoutes = require('./routes/destinations');
const favoritesRoutes = require('./routes/favorites');
const tripRoutes = require('./routes/trips');
const userRoutes = require('./routes/users');
require('dotenv').config();

const app = express();
app.use(express.json());
app.use('/api/auth', authRoutes);// This is for user registration and login, generated by ai lah later phrase 2 we add more auth features like JWT, password hashing, etc.)
app.use('/api/users', userRoutes);
app.use('/api/trips', tripRoutes);

// Connect to MongoDB
mongoose.connect(process.env.MONGO_URL, {
  serverSelectionTimeoutMS: 3000 // stop trying after 3s
})
.then(() => console.log("MongoDB connected"))
.catch(err => {
  console.log("MongoDB failed try to resolve connection:");
  console.log(err.message);
});

// API Routes
app.use('/api', tripRoutes);
app.use('/api/destinations', destinationRoutes);
app.use('/api/favorites', favoritesRoutes);

// Serve all static files from public/
app.use(express.static('public'));

app.listen(3000, () => console.log('Server running on http://localhost:3000'));
